### ISSUE TITLE
Decode string value with "+" inside issue

### ISSUE THREAD

**Issue by dmitry-rivlin-vrp** [bblanchon/ArduinoJson#496] opened 2017-05-02 17:06 UTC
const char defaultConfig[] PROGMEM = R"=====(
{
    "HTTP": {
    "isEnabled": true,
    "httpPort": 80,
    "fileNotFound": "/cfg/404.html",
    "mymeTypes": {
      "html": "text/html",
      "log": "plain/text",
      "css": "text/css",
      "json": "application/json",
      "gz": "application/x-gzip",
      "js": "application/javascript",
      "ico": "image/ico",
      "woff2": "font/woff2",
      "svg": "image/svg+xml",
      "png": "image/png"
    }
  }
}
)=====";

DynamicJsonBuffer jsonBuffer;

 JsonObject& jsonCfg = jsonBuffer.parseObject(defaultConfig);

when i see value in jsonCfg["HTTP"][mimeTypes"]["svg"] i see **"image/svg xml"** instead **"image/svg+xml"**

**Comment by bblanchon** [comment] 2017-05-02 19:27
Hi @dmitry-rivlin-vrp 

I was not able to reproduce this bug.
However, I saw an typo in your code: in the input it's written "mymeTypes" instead of "mimeTypes".

Can you double check ?
Regards

**Comment by bblanchon** [comment] 2017-05-10 08:31
@dmitry-rivlin-vrp any progress?

**Comment by dmitry-rivlin-vrp** [comment] 2017-05-10 14:52
I just prepared workaround.

**Comment by bblanchon** [comment] 2017-05-10 15:48
Do you still think there is a bug in the library?

**Comment by dmitry-rivlin-vrp** [comment] 2017-05-11 03:50
I am not sure. Probably i have issue with my implementation.

For example if i use \+ instead + all works as designed.

**Comment by bblanchon** [comment] 2017-05-11 16:08
I don't think the problem is related to ArduinoJson.
I'm closing this issue.
Please reopen if needed.

**Closed by bblanchon** 2017-05-11 16:08 UTC
