### ISSUE TITLE
Problem with Array in quotation marks

### ISSUE THREAD

**Issue by kugelkopf123** [bblanchon/ArduinoJson#903] opened 2019-02-03 18:26 UTC
Hey! 
For three days I tried in vain to parse a JSON string (stream).
Today I found out that it is not possible to parse a JSON string that has a quotation mark in front of the square brackets.
Unfortunately, I can not query the JSON string differently.

Do you have an idea how I get to the data?
Attached the complete JSON strings and my code.

I have to have all the data but I focus on the arrays "javascript.0.Wetterstation.HistTemp1Date" and "javascript.0.Wetterstation.HistTemp1" first.
I am completely desperate and can not continue.

Greetings...
```

{
  "javascript.0.Wetterstation.TempDraussenMin": {
    "val": -0.1,
    "ack": false,
    "ts": 1549216440089,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549216440080
  },
  "javascript.0.Wetterstation.TempDraussenMax": {
    "val": 5.5,
    "ack": false,
    "ts": 1549198440031,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549198440031
  },
  "javascript.0.Wetterstation.TempDraussenMinTime": {
    "val": "18:54:00 - 03.02.2019",
    "ack": false,
    "ts": 1549216440096,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549216440096
  },
  "javascript.0.Wetterstation.TempDraussenMaxTime": {
    "val": "13:54:00 - 03.02.2019",
    "ack": false,
    "ts": 1549198440034,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549198440034
  },
  "javascript.0.Wetterstation.LastResetMinMax": {
    "val": "11:45:40 - 03.02.2019",
    "ack": false,
    "ts": 1549190740415,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549190740415
  },
  "javascript.0.Wetterstation.UpdateAnAus": {
    "val": false,
    "ack": false,
    "ts": 1548212875725,
    "q": 0,
    "from": "system.adapter.admin.0",
    "lc": 1548212875725
  },
  "javascript.0.Wetterstation.ResetMinMax": {
    "val": true,
    "ack": false,
    "ts": 1549190740396,
    "q": 0,
    "from": "system.adapter.web.0",
    "lc": 1547985029727
  },
  "javascript.0.Wetterstation.HistTemp1Date": {
    "val": "[\"2019-1-31 20:00:00\",\"2019-1-31 21:00:00\",\"2019-1-31 22:00:00\",\"2019-1-31 23:00:00\",\"2019-2-1 00:00:00\",\"2019-2-1 01:00:00\",\"2019-2-1 02:00:00\",\"2019-2-1 03:00:00\",\"2019-2-1 04:00:00\",\"2019-2-1 05:00:00\",\"2019-2-1 06:00:00\",\"2019-2-1 07:00:00\",\"2019-2-1 08:00:00\",\"2019-2-1 09:00:00\",\"2019-2-1 10:00:00\",\"2019-2-1 11:00:00\",\"2019-2-1 12:00:00\",\"2019-2-1 13:00:00\",\"2019-2-1 14:00:00\",\"2019-2-1 15:00:00\",\"2019-2-1 16:00:00\",\"2019-2-1 17:00:00\",\"2019-2-1 18:00:00\",\"2019-2-1 20:00:00\",\"2019-2-1 21:00:00\",\"2019-2-1 22:00:00\",\"2019-2-1 23:00:00\",\"2019-2-2 00:00:00\",\"2019-2-2 01:00:00\",\"2019-2-2 02:00:00\",\"2019-2-2 03:00:00\",\"2019-2-2 04:00:00\",\"2019-2-2 05:00:00\",\"2019-2-2 06:00:00\",\"2019-2-2 07:00:00\",\"2019-2-2 08:00:00\",\"2019-2-2 09:00:00\",\"2019-2-2 10:00:00\",\"2019-2-2 11:00:00\",\"2019-2-2 12:00:00\",\"2019-2-2 13:00:00\",\"2019-2-2 14:00:00\",\"2019-2-2 15:00:00\",\"2019-2-2 16:00:00\",\"2019-2-2 17:00:00\",\"2019-2-2 18:00:00\",\"2019-2-2 19:00:00\",\"2019-2-2 20:00:00\",\"2019-2-2 21:00:00\",\"2019-2-2 22:00:00\",\"2019-2-2 23:00:00\",\"2019-2-3 00:00:00\",\"2019-2-3 01:00:00\",\"2019-2-3 02:00:00\",\"2019-2-3 03:00:00\",\"2019-2-3 04:00:00\",\"2019-2-3 05:00:00\",\"2019-2-3 06:00:00\",\"2019-2-3 07:00:00\",\"2019-2-3 08:00:00\",\"2019-2-3 09:00:00\",\"2019-2-3 10:00:00\",\"2019-2-3 11:00:00\",\"2019-2-3 12:00:00\",\"2019-2-3 13:00:00\",\"2019-2-3 14:00:00\",\"2019-2-3 15:00:00\",\"2019-2-3 16:00:00\",\"2019-2-3 17:00:00\",\"2019-2-3 18:00:00\"]",
    "ack": false,
    "ts": 1549217316165,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549217316165
  },
  "javascript.0.Wetterstation.HistTemp1": {
    "val": "[-1.24,-0.67,-0.13,-0.58,-1.26,-1.81,-1.49,-0.75,-0.52,-0.4,-0.04,0,-0.13,-0.06,0.37,0.87,1.51,1.78,3.05,3.7,3.7,3.06,2.48,2.09,1.9,0.93,-0.28,-0.64,-0.49,-0.36,-0.31,-0.06,0.15,0.42,0.65,0.58,0.39,0.62,1.09,1.31,0.83,0.71,1.04,0.94,0.5,0.59,0.54,0.5,0.56,0.4,-0.34,-0.13,0.11,0.2,-0.02,-0.37,0.03,-0.21,-0.53,-1.05,-0.86,-0.49,0.36,1.77,3.86,4.96,5.13,5.21,4.14,1.48]",
    "ack": false,
    "ts": 1549217316168,
    "q": 0,
    "from": "system.adapter.javascript.0",
    "lc": 1549217288962
  }
}

```
```
if (client.connect(host, 8088))

  {
    Serial.println("connected]");

    Serial.println("[Sending a request]");
    client.print(String("GET /getBulk/javascript.0.Wetterstation.*") + " HTTP/1.1\r\n" +
                 "Host: " + host + "\r\n" +
                 "Connection: close\r\n" +
                 "\r\n"
                );



    char status[32] = {0};
    client.readBytesUntil('\r', status, sizeof(status));
    if (strcmp(status, "HTTP/1.1 200 OK") != 0) {
      Serial.print(F("Unexpected response: "));
      Serial.println(status);
       return;
    }
    char endOfHeaders[] = "\r\n\r\n";
    if (!client.find(endOfHeaders)) {
      Serial.println(F("Invalid response"));
      return;
    }

    Serial.println("[Response:]");
    while (client.connected() || client.available())
    {
      if (client.available())
      {
        String line = client.readStringUntil('\n');
        Serial.println(line);
      }
    }


    client.stop();
    Serial.println("\n[Disconnected]");
  }
  else
  {
    Serial.println("connection failed!]");
    client.stop();
  }

  Serial.println(client);
  
  const int capacity = 4081;
  DynamicJsonBuffer jsonBuffer(capacity);

  JsonObject&  parsed = JSONBuffer.parseObject(client);
  JsonArray& values = parsed[javascript.0.Wetterstation.HistTemp1][“val”];
  

```

**Comment by bblanchon** [comment] 2019-02-05 08:07
Hi @kugelkopf123,

If I understand correctly, the problem is that a string contains an array.

We can summarize like that:

```json
{
   "a": "[1,2,3]" 
}
```

Assuming that you want to get a [JsonArray](https://arduinojson.org/v5/api/jsonarray/?utm_source=github&utm_medium=issues) from the string `a`, you need to call [`parseArray()`](https://arduinojson.org/v5/api/jsonbuffer/parsearray/?utm_source=github&utm_medium=issues) on the string:

```c++
DynamicJsonBuffer jb(capacity);

JsonObject& root = jb.parseObject(input);
JsonArray& array = jb.parseArray(root["a"].as<char*>());
```

Regards,
Benoit

**Comment by kugelkopf123** [comment] 2019-02-05 16:06
I just do not understand. It does not want to work!

Use the same code as in my first post. 
```
const int capacity = 4078;
DynamicJsonBuffer jsonBuffer(capacity);

  JsonObject&  root = jsonBuffer.parseObject(client);
    root.prettyPrintTo(Serial);

  JsonArray& values = jsonBuffer.parseArray(root["javascript.0.Wetterstation.HistTemp1"]["val"].as<char*>());
  values.prettyPrintTo(Serial);
  if (values.success()) {


    Serial.println("successful");

    }
    else {

    Serial.println("not successful");
    }
```

The Output vor root.prettyPrintTo(Serial) and values.prettyPrintTo.. and values success:

```
{}
[]
not successful
```

**Comment by bblanchon** [comment] 2019-02-06 10:51
Hi @kugelkopf123,

Are you sure that the parsing succeeded in the first place?
Can you check [JsonObject::success()](https://arduinojson.org/v5/api/jsonobject/success/?utm_source=github&utm_medium=issues)?

If it returns `false`, check out [Why parsing fails?](https://arduinojson.org/v5/faq/why-parsing-fails/?utm_source=github&utm_medium=issues)

Regards,
Benoit

**Comment by kugelkopf123** [comment] 2019-02-07 02:19
I found the mistake and could solve it thanks to your help! Many Thanks! 

Other question: Im using an ESP8266 4MB.Because of the many arrays I need to import, I need quite a bit of memory. Now I found that in the ESP32_OWM_current_Forecast_75_epaper_v8_GxEPD sketch.

```
bool DecodeWeather(String json, String Type) {
  Serial.println("Received a JSON string of size : "+String(json.length()));
  Serial.print(F("Creating object...and "));
  // allocate the JsonDocument
  DynamicJsonDocument doc(20*1024);
  // Deserialize the JSON document
  DeserializationError error = deserializeJson(doc, json);
  // Test if parsing succeeds.
  if (error) {
    Serial.print(F("deserializeJson() failed: "));
    Serial.println(error.c_str());
    return false;
  }
  // convert it to a JsonObject
  JsonObject root = doc.as<JsonObject>();
  Serial.println(" Decoding " + Type + " data");
```
Would that be better?
I know it runs on v6.
Greetings.

**Comment by bblanchon** [comment] 2019-02-08 12:27
Hi @kugelkopf123,

You're welcome; I'm glad you found the solution.
What was the problem?

I'm not sure I understand your question:
* If you're asking whether v6 is better than v5, then yes, but it's still in beta.
* If you're asking whether v6 uses less memory than v5, then probably, but you should check with [the assistant](https://arduinojson.org/v6/assistant/?utm_source=github&utm_medium=issues).

See also:

* [Can I parse a JSON input that is too big to fit in memory?](https://arduinojson.org/v5/faq/can-i-parse-a-json-input-that-is-too-big-to-fit-in-memory/?utm_source=github&utm_medium=issues)

Regards,
Benoit

**Comment by kugelkopf123** [comment] 2019-02-11 11:55
Hey! Sorry that I'll get in touch now.
There was a problem with the parsing of the stream. Your idea to test the JSON object first let me recognize the error. Thanks!
So far I did not have time to work on my project. Thanks for the links, I will look at them!

**Comment by bblanchon** [comment] 2019-02-11 16:18
You're welcome @kugelkopf123.
I'm closing this issue now; please open a new one if you need further assistance.

**Closed by bblanchon** 2019-02-11 16:18 UTC
