### ISSUE TITLE
Unable to compile ArduinoJSON on ClearCore board

### ISSUE THREAD

**Issue by sfactor33** [bblanchon/ArduinoJson#1947] opened 2023-07-13 23:17 UTC
Unable to compile ArduinoJSON in Arduino IDE V1.8.19 using ClearCore board package V1.1.2.

Fixed as suggested by https://forum.arduino.cc/t/solved-esp8266-pgm-read-ptr-error-const-void-is-not-a-pointer-to-object-type/1037766/6

#define ARDUINOJSON_ENABLE_PROGMEM 0   
#include <ArduinoJson.h>

With the added #define, it compiles and JsonGeneratorExample works properly.

**Environment**  
Here is the environment that I used:
ClearCore board using SAMD5xN processor
Arduino IDE V1.8.19 using ClearCore board package V1.1.2

**Compiler output**    
In file included from C:\Users\MainUser\AppData\Local\Arduino15\packages\ClearCore\hardware\sam\1.1.2\cores\arduino/api/ArduinoString.h:32:0,
                 from C:\Users\MainUser\AppData\Local\Arduino15\packages\ClearCore\hardware\sam\1.1.2\cores\arduino/api/Print.h:24,
                 from C:\Users\MainUser\AppData\Local\Arduino15\packages\ClearCore\hardware\sam\1.1.2\cores\arduino/api/Stream.h:24,
                 from C:\Users\MainUser\AppData\Local\Arduino15\packages\ClearCore\hardware\sam\1.1.2\cores\arduino/api/Client.h:22,
                 from C:\Users\MainUser\AppData\Local\Arduino15\packages\ClearCore\hardware\sam\1.1.2\cores\arduino/api/ArduinoAPI.h:29,
                 from C:\Users\MainUser\AppData\Local\Arduino15\packages\ClearCore\hardware\sam\1.1.2\cores\arduino/Arduino.h:24,
                 from sketch\JsonGeneratorExample.ino.cpp:1:
D:\My Documents\Arduino\libraries\arduino_745846\src/ArduinoJson/Polyfills/pgmspace_generic.hpp: In instantiation of 'const T* ArduinoJson::V6212PB::detail::pgm_read(const T* const*) [with T = char]':
D:\My Documents\Arduino\libraries\arduino_745846\src/ArduinoJson/Deserialization/DeserializationError.hpp:85:42:   required from here
C:\Users\MainUser\AppData\Local\Arduino15\packages\ClearCore\hardware\sam\1.1.2\cores\arduino/api/deprecated-avr-comp/avr/pgmspace.h:106:29: error: 'const void*' is not a pointer-to-object type
 #define pgm_read_ptr(addr) (*(const void *)(addr))
                            ~^~~~~~~~~~~~~~~~~~~~~~
exit status 1
Error compiling for board Teknic ClearCore.

**Comment by bblanchon** [comment] 2023-07-15 08:23
Hi @sfactor33,

Thanks for reporting this issue.
This bug is not in ArduinoJson but in [ClearCore's Arduino core](https://github.com/Teknic-Inc/ClearCore-Arduino-wrapper/blob/170f7638e99261bfde4961a2ab0876bd43dbe295/cores/arduino/api/deprecated-avr-comp/avr/pgmspace.h#L106) and they inherited it from [Arduino's hardware independent core](https://github.com/arduino/ArduinoCore-API/pull/118).

I opened a [Pull Request](https://github.com/Teknic-Inc/ClearCore-Arduino-wrapper/pull/4) there, so I'll close this issue.
Until the fix is available, you can set [`ARDUINOJSON_ENABLE_PROGMEM`](https://arduinojson.org/v6/api/config/enable_progmem/) to 0; this platform doesn't support PROGMEM anyway.

Duplicate of #1442, #1519, #1536, #1591, #1676, #1790, and #1874.

Best regards,
Benoit

**Closed as not planned by bblanchon** 2023-07-15 08:23 UTC
Labels: duplicate
